### ISSUE TITLE
[Adapters] Config.go: lint error due to long SVG line

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-adapter-library#101]
Given that we’re incorporating full images (SVGs) into Meshery Adapter config.go files, we’re going to want to consider changing the lint rules to accommodate. Here is an example failure - https://github.com/meshery/meshery-cilium/pull/104/files#file-build-config-go-L29

[Slack Message](https://layer5io.slack.com/archives/C017NA80S66/p1673823930918579)

**Comment by b0id** [comment]
https://github.com/meshery/meshery-cilium/pull/106

**Comment by leecalcote** [comment]
Fixed
