### ISSUE TITLE
[chore] update Go to 1.21, and update relevant pkgs

### ISSUE THREAD

**Issue by saurabh100ni** [meshery/meshery-adapter-library#125]
### Desired Behaviour
Need to update `Go` to `1.21` in `go.mod` and in `Dockerfile`, and also `Makefile`

- Minor chore on updating `meshkit` and `meshery-adapter-library`

**Comment by rj2704** [comment]
Hi @Ghat0tkach,  Assign it to me I can fix these issue.

**Comment by sadamhussain-m** [comment]
I would like to work on this issue.

**Comment by Ghat0tkach** [comment]
there you go @rj2704

**Comment by rj2704** [comment]
Hi @saurabh100ni, and @Ghat0tkach, Please review these PRs if you have the time. In that case, we can merge it if everything seems fine.

**Comment by saurabh100ni** [comment]
@ritiksaxena124 @Rajdip019 //
