### ISSUE TITLE
to fix error in "Slack Notify on Star" Job under GitHub Actions

### ISSUE THREAD

**Issue by captain-Akshay** [meshery/meshery-adapter-library#127]
**Description**
Under GitHub Actions of this repository "[Slack Notify on Star](https://github.com/meshery/meshery-adapter-library/actions/runs/5435590636)" job is failing for which [Slack.yaml](https://github.com/meshery/meshery-adapter-library/blob/master/.github/workflows/slack.yml) is to be Updated.

**Expected Behavior**

To fix this issue, update the code of [slack.yaml](https://github.com/meshery/meshery-adapter-library/blob/master/.github/workflows/slack.yml)

---
 ### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by captain-Akshay** [comment]
i would like to work on this issue !

**Comment by saurabh100ni** [comment]
Go For it @captain-Akshay 😎🚀
