### ISSUE TITLE
Move from MeshModel to Model

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-adapter-library#153]
We're in need of having `RegisterMeshModelComponents` changed to `RegisterMeshModelComponents` inside of the Meshery Adapter Library. Let's do what we can to get away from `MeshModel` over to `Model`.

_Originally posted by @leecalcote in https://github.com/meshery/meshery-nighthawk/issues/46#issuecomment-1968263210_

**Comment by leecalcote** [comment]
@gyohuangxin I wonder if you might be able to undertake this. Be aware that once the change is made and a new version of the library released, each adapter will need a small update. // @MUzairS15

**Comment by gyohuangxin** [comment]
@leecalcote Yes, @MUzairS15 mention it before.  I can take this.
