### ISSUE TITLE
[Chore] Upgrade to Golang 1.23.4

### ISSUE THREAD

**Issue by devhindo** [meshery/meshery-adapter-library#163]
#### Current Behavior
Project is running golang 1.21.8.
 
#### Desired Behavior
Project need updated to golang 1.23.4
 
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
* 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
* 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
* 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   
* Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
* 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
* 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by akv2011** [comment]
I would love to work on this , can you guide me a starting point

**Comment by devhindo** [comment]
Hello @akv2011! so this issue is resolved via this [pr](https://github.com/meshery/meshery-adapter-library/pull/164). Please check it out, It would help you get familiar with the project more. There are other adapters that needs to be updated. You can check this [issue](https://github.com/meshery/meshery/issues/12829) if you want to participate. and feel free to ask about anything!

**Comment by akv2011** [comment]
Thank you, the doubt i had in the  issue [#12916](https://github.com/meshery/meshery/issues/12916)
you had referenced the need for updation of meshery-adapter-library and so on ..to compile linkerd ,I was hoping  if it's not a hassle  you could guide me on it if any refrences , am fairly new to meshery ..sorry!.
