### ISSUE TITLE
It would be ideal if we did not hard code name operations like this.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-adapter-library#20]
It would be ideal if we did not hard code name operations like this. 

Instead, adapters will encode the mechanics of the operation (i.e. `kubectl`) and operation type (`apply`) and operation media (single file, file path to a folder containing manifests, or URL to an endpoint that returns a manifest) externalizing the operation names ("BookInfo"), supported operation verbs (apply, delete) and supported versions (version of BookInfo) as config outside of the go code.

_Originally posted by @leecalcote in https://github.com/layer5io/meshery-adapter-library/pull/18#discussion_r524836860_

**Comment by mgfeller** [comment]
Actually, I think we are well prepared. If everything that we think should/ could be externalized is put into the config (handled by a config provider like Viper) then that can quite easily be externalized once we have figured out how to codify the operation executor and verb, and to make this open to extension by adapters. Meanwhile, the hard coded keys are used to select executor in the code, which will help to identify the necessary/common executor and how they are used. E.g. in the corresponding switch statement in the consul adapter, all operations are executed using the same code.

@leecalcote @kumarabd

**Comment by kumarabd** [comment]
This can be closed I believe. @mgfeller @leecalcote ?

**Comment by mgfeller** [comment]
I'd like to keep this open, as a future task for the longer-term plan and as place to discuss this. @leecalcote @kumarabd

**Comment by leecalcote** [comment]
Seeing the stalebot swing by here, I'll note that if we're still looking to keep this open, applying `issue/willfix` label has the effect of telling the stalebot to leave the issue alone.

**Comment by mgfeller** [comment]
Ah, yes, this one again. Maybe we should move this to a/the design document.

**Comment by kumarabd** [comment]
Keeping this open as requested by @mgfeller

**Comment by leecalcote** [comment]
With patterns on the way in, we will essentially have a new system (MeshOps v2 , if you will) and I believe the use of patterns will more or less eliminate the concern here.

**Comment by mgfeller** [comment]
Cool, looking forward to that, and closing the issue.
