### ISSUE TITLE
Incorporate Adapter Version # at buildtime

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-adapter-library#25]
**Current Behavior**
Meshery adapters have their version # hardcoded. See https://github.com/layer5io/meshery-adapter-library/blob/master/common/defaults.go#L34

**Desired Behavior**
An adapter's version number should be retrieved at buildtime from the CI workflow.

---
**Resources**

**Alternatives / Additional Context**

**Comment by mgfeller** [comment]
I think adding a new proto functions is a good solution. Maybe we could add a more general function, like `MeshInfo`, with a map, so that we can send over additional information without having to change the proto definition. Also, we'd like to send over both `GIT_VERSION` and `GIT_COMMITSHA`.

The function call can be handled in `meshery-adapter-library` , like `GetName` (`adapter/spec.go:30`), which again is called by the proto function `MeshName` (`api/grpc/handlers.go:36`). There is actually already a function `GetVersion` in `adapter/spec.go`, but appears unused. Maybe it needs modification.

In the adapters, the `build-and-release.yaml` and `Dockerfile` have to be modified, and in `main.go` (possibly), the version in the config has to be set.
Similar has been done in `meshery` ,  `build-and-release.yaml` :
`--build-arg GIT_COMMITSHA=${GITHUB_SHA::7} --build-arg GIT_VERSION=${GITHUB_REF/refs\/tags\//}`
 `Dockerfile` :
`-X main.version=$GIT_VERSION -X main.commitsha=$GIT_COMMITSHA`

Any more general functionality should go into `meshkit`, but right now I can't see any.

**Comment by mgfeller** [comment]
Of course, it should be `ServerInfo` rather than `MeshInfo` for this issue, my mistake. Also, the `GetVersion` returns the mesh version. 
Personally I'd prefer `AdapterInfo`, because it describes the function, and not the implementation, as `ServerInfo` does. We usually use the term 'adapter' rather than 'server' as well.

**Comment by leecalcote** [comment]
@mgfeller, you're right that there is an argument for inclusion of this component-version-reporting functionality to land in MeshKit. For example, consider this mockup:

![Settings](https://user-images.githubusercontent.com/7570704/103685190-6841fe00-4f52-11eb-9418-ceded96d90e5.png)

If you have motioned to move this enhancement to `meshkit`, then I think I have just seconded that motion. :)

// @kumarabd @utkarsh-pro @uds5501

**Comment by mgfeller** [comment]
From Slack:

![image](https://user-images.githubusercontent.com/1214008/103756325-802b8780-500f-11eb-8e3e-d6dd17e7c6aa.png)

**Comment by mgfeller** [comment]
> If you have motioned to move this enhancement to `meshkit`, then I think I have just seconded that motion. :)

Hmm... I might have mentioned something related to that before (but can't find the conversation).

The individual components will expose this information. For adapters, this means implementing it (also) as a function in the gRPC service, in `meshery-adapter-library` (leveraging the existing injection mechanisms to expose info from contained in the config).

How are other components exposing information about themselves? 

Client functionality could of course be implemented in `meshkit`. 

A `ComponentInfo` message could be defined centrally in `meshkit` and used in other components (name, type, status, health, version, commit_sha, id, description, ...).

Could `meshops.proto` be moved from `meshery` to `meshkit`?

// @leecalcote @kumarabd @uds5501 @utkarsh-pro

**Comment by leecalcote** [comment]
@mgfeller, good call. @uds5501 the `/info` endpoint in meshkit makes component version available. See https://github.com/layer5io/meshkit/tree/master/protobuf.

**Comment by mgfeller** [comment]
@leecalcote @uds5501 yes, I thought something along those lines, but more fields, or a map, or a composed message. This is controller info, though, not component.
I envisaged something like `/protobuf/component/info.proto` with name, id, status, health ++ that would be imported by e.g. controller and adapter service (i.e. into https://github.com/layer5io/meshery/blob/master/meshes/meshops.proto), used in service responses or events. every service could e.g. expose a function/endpoint/event `ComponentInfo`.

**Comment by leecalcote** [comment]
Sounds good to me, @mgfeller

**Comment by leecalcote** [comment]
YES! 😄 
<img width="616" alt="Screen Shot 2021-02-21 at 8 19 03 PM" src="https://user-images.githubusercontent.com/7570704/108648984-13b2fd80-7482-11eb-828e-19ea25a07fc8.png">

**Comment by mgfeller** [comment]
https://github.com/layer5io/meshery/issues/2449

**Comment by mgfeller** [comment]
Looks like it would be preferable to merge https://github.com/layer5io/meshery-adapter-library/pull/34 first.

**Comment by leecalcote** [comment]
Quick check... this component version information is now coming through and is available to Meshery Server, correct? If so, it's time for an issue to expose this in Meshery UI. 

Excited about this one. 😄

**Comment by mgfeller** [comment]
I'll check the status on this one. And create a Meshery UI issue if it doesn't exist and hasn't been implemented.

// @leecalcote

**Comment by mgfeller** [comment]
// @leecalcote 

```
dev/meshery-run/wo4Ockd8Bo7Ke4G3 
❯ grpcurl --plaintext 127.0.0.1:10002 meshes.MeshService.ComponentInfo
{
  "type": "adapter",
  "name": "CONSUL",
  "version": "none",
  "gitSha": "none"
}
dev/meshery-run/wo4Ockd8Bo7Ke4G3 
❯ grpcurl --plaintext 127.0.0.1:10008 meshes.MeshService.ComponentInfo
Error invoking method "meshes.MeshService.ComponentInfo": failed to query for service descriptor "meshes.MeshService": server does not support the reflection API
dev/meshery-run/wo4Ockd8Bo7Ke4G3 
❯ grpcurl --plaintext 127.0.0.1:10000 meshes.MeshService.ComponentInfo
{
  "type": "adapter",
  "name": "ISTIO",
  "version": "v0.5.9",
  "gitSha": "fa47813"
}
dev/meshery-run/wo4Ockd8Bo7Ke4G3 
❯ grpcurl --plaintext 127.0.0.1:10007 meshes.MeshService.ComponentInfo
{
  "type": "adapter",
  "name": "KUMA",
  "version": "v0.5.5",
  "gitSha": "a116b03"
}
dev/meshery-run/wo4Ockd8Bo7Ke4G3 
❯ grpcurl --plaintext 127.0.0.1:10001 meshes.MeshService.ComponentInfo
{
  "type": "adapter",
  "name": "LINKERD",
  "version": "v0.5.5",
  "gitSha": "8cf2b32"
}
dev/meshery-run/wo4Ockd8Bo7Ke4G3 
❯ grpcurl --plaintext 127.0.0.1:10004 meshes.MeshService.ComponentInfo
{
  "type": "adapter",
  "name": "NETWORK_SERVICE_MESH"
}
dev/meshery-run/wo4Ockd8Bo7Ke4G3 
❯ grpcurl --plaintext 127.0.0.1:10009 meshes.MeshService.ComponentInfo
{
  "type": "adapter",
  "name": "OPEN_SERVICE_MESH",
  "version": "none",
  "gitSha": "none"
}
dev/meshery-run/wo4Ockd8Bo7Ke4G3 
❯ grpcurl --plaintext 127.0.0.1:10006 meshes.MeshService.ComponentInfo
{
  "type": "adapter",
  "name": "TRAEFIK_MESH",
  "version": "v0.5.6",
  "gitSha": "9029d0b"
}

```

**Comment by leecalcote** [comment]
Progress. In a non-obvious way, we've begun to expose some of this in the UI and show to the user onhover of an adapter chip.

<img width="480" alt="Screen Shot 2021-06-22 at 3 50 40 PM" src="https://user-images.githubusercontent.com/7570704/122997431-9fc22c80-d371-11eb-8fef-a21c1f389607.png">

@ramrodo, heads-up: we might not be including build information in each of the Meshery Adapter build workflows, at least not for OSM, NSM, Consul, CPX. It _should be_ the case that we can propagate workflow updates to include version and tag into these adapter repos with relatively little pain.

**Comment by mgfeller** [comment]
Looks like the Consul-adapter just needs to be released, the changes have been made:

![image](https://user-images.githubusercontent.com/1214008/123041350-79de6b80-d3f5-11eb-8db8-b05a8ae15602.png)

**Comment by mgfeller** [comment]
For meshery-nsm see https://github.com/meshery/meshery-nsm/issues/124

**Comment by mgfeller** [comment]
meshery-osm code looks also good, looks like just a release is needed?

![image](https://user-images.githubusercontent.com/1214008/131216052-017ee6ee-d68a-4a8e-b262-25f5251738d2.png)

**Comment by mgfeller** [comment]
I suggest this general issue can be closed now - and will be if no-one objects within a few days or so.

// @leecalcote

**Comment by mgfeller** [comment]
Hmm I would have expected that e.g. Consul edge-latest returns `version: edge-latest` but it doesn't afaics...

**Comment by mgfeller** [comment]
> Hmm I would have expected that e.g. Consul edge-latest returns `version: edge-latest` but it doesn't afaics...

`main.version` etc needs to be `var` not `const`

**Comment by mgfeller** [comment]
> > Hmm I would have expected that e.g. Consul edge-latest returns `version: edge-latest` but it doesn't afaics...
> 
> `main.version` etc needs to be `var` not `const`
> 

Same for `mesher-osm`...

**Comment by mgfeller** [comment]
Consul, NSM, OSM return version and gitsha now, tested with edge and using 
`grpcurl --plaintext 127.0.0.1:<port> meshes.MeshService.ComponentInfo`
(CPX needs to be updated to meshery-adapter-library by the looks of it.)

closing this issue now :tada:
