### ISSUE TITLE
[CI] Add new and modify existing targets in Makefile related to code quality

### ISSUE THREAD

**Issue by mgfeller** [meshery/meshery-adapter-library#5]
**Current Behavior**

* Currently, there is no target to fix `gofmt` and `goimport` warnings from `golangci-lint`, and to tidy mod
* the target running `golangci-lint`is called `check`(similar for clearing its cache)
* Neither is `go mod verify` executed, and that could be useful too

**Desired Behavior**

* Target `golangci-run` called from target `check`, or rename `check` to `golangci-run`
* Target `clean`, executing `go clean` and `golangci-lint cache clean`
* Target `verify` executing `go mod verify`
* Target `tidy` executing `go mod tidy`,  `gofmt -w .`, `goimports -w .`

---
**Resources**

Makefiles in other Layer5 (adapter) repositories.

**Comment by mgfeller** [comment]
@kumarabd why was this issue closed? As far as I can see, it has not been implemented?

**Comment by kumarabd** [comment]
@mgfeller that was my mistake, was going to reopen it.

**Comment by mgfeller** [comment]
I think it could be useful to establish a standard / template (and mark it as such) that we just can copy to the various repositories, to implement this quickly, including the corresponding tool config and entries in the ci workflow. Or do we already have that? 
// @ramrodo

**Comment by ramrodo** [comment]
@mgfeller Sounds great to have a template! There is no template of `Makefile` for those common tools/targets in the `layer5io/layer5-repo-template` repo. So, I created this issue in the template repo to track this task and be taken for anyone:
https://github.com/layer5io/layer5-repo-template/issues/9

**Comment by mgfeller** [comment]
@Aisuko which of the existing local checks in the layer5 repos would you recommend as starting point?

**Comment by Aisuko** [comment]
> @Aisuko which of the existing local checks in the layer5 repos would you recommend as starting point?

@mgfeller Thank you, for my personal, I'd like to  recommend https://github.com/layer5io/meshsync/blob/v0.1.2/Makefile , but we should replace the `golangci.yml`, because it was included too many configurations items we did not use.
