### ISSUE TITLE
[Refactor] Update OpenTelemetry implementation

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery-adapter-library#92]
**Current Behavior**

Right now, the current package for OpenTelemetry is at ` v1.3.0`.

As of right now, the latest package is at `v1.10.0` which have some major changes in the last couple years. This will require a refactor, and can also assist in the upgrading from Go 1.17 to 1.19.

Reference:

https://pkg.go.dev/go.opentelemetry.io/otel

**Desired Behavior**

By refactoring, we will also be able to update according to the rest of the Go projects that replies on this module.

---
**Resources**

**Alternatives / Additional Context**

**Comment by leecalcote** [comment]
@jbyers19... the one that you've been waiting for. 😉

**Comment by acald-creator** [comment]
@jbyers19 I started a separated local branch to refactor Jaeger but you are welcome to contribute or take this item if you want?

**Comment by acald-creator** [comment]
Will be working on this issue

**Comment by leecalcote** [comment]
Oh, nice. 🙂

**Comment by leecalcote** [comment]
@jbyers19 a project for your holiday downtime?

**Comment by acald-creator** [comment]
bump, I was working on this but got sidetracked with Next.js upgrade.

I am partially done with this actually. Just need to finish it and submit the PR.

**Comment by acald-creator** [comment]
bump

**Comment by acald-creator** [comment]
bump
